### PR TITLE
Feature writemode

### PR DESCRIPTION
**Pull request by jooneyp**
Added writemode with update mode.
It works nicely but I'm really new to Ruby and I can't sure my code is clean.
Please review my codes.

### CODE REVIEW

**Comment by jooneyp** [comment]
Any comments?

**Comment by ayoy** [comment]
Yes, so many that I copied your code to my branch and started working on it myself. Then I had to stop because life kicked in, but I hope I'll figure this out this week.

* The param needs to be called `write_mode` and not `writemode`.
* The UI message outputting the write mode to the console is unnecessary.
* The wording for parameters documentation is poor (_Revision no. to update_ doesn't say too much).
* Ideally, the `write_mode` parameter should be optional, defaulting to `:add`, but when `update_rev` is present then `write_mode` has to be equal to `:update` (or not present too, but defaulting to `:update`). I can't make it work with Fastlane parameters optionality yet.
* I was getting some weird errors from Dropbox when trying to test write modes, can't remember those now, might have been unrelated though.
* You forgot tests.

**Comment by jooneyp** [comment]
Okay, thanks for you kindness.
Since I am new to Ruby and just ended my first year of developer, I can learn so many things from your comments.
I'll keep going for this project for good.

**Comment by ayoy** [comment]
@jooneyp I added write mode and made 0.2.0 release. Please verify if it works for you. Thanks for the patch!

**Comment by jooneyp** [comment]
Works like a charm.
Thanks for your help!🙌

**Pull request merged**
